services:
  manhua-app:
    container_name: manhua
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    env_file:
      - .env
    volumes:
      - ./server/data:/app/server/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - manhua-network

networks:
  manhua-network:
    driver: bridge

volumes:
  manhua_data:
    driver: local
